version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0
    - 2.0.0-beta.54
    - 2.0.0-beta.58
    - 2.0.0-beta.61
    - 2.0.0-beta.62
    - 2.0.0-beta.64
    - 2.0.0-beta.65
    - 2.0.0-beta.66
    - 2.0.0-beta.67
    - 2.0.0-beta.69
    - 2.0.0-beta.70
    - 2.0.1
    - 2.0.2
    - 2.0.3
    - 2.0.4
    - 2.0.5
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.2.1
  - dependency-name: react-redux
    versions:
    - 7.2.3
